### ISSUE TITLE
host system call

### ISSUE THREAD

**Issue by Daparrag** [gnuarmeclipse/openocd#13]
Dear all, 

I'm working with the STM32F401RE board in the semihosting mode, However was impossible to execute system call's related with the command processor (shell(LINUX) or the command line(WINDOWS)) such as "dir, ls -l", I suppose that it is because Openocd doesn't support such kind of SYSTEM_CALLS.

If my affirmation is correct, I'm Interesting in implementing such functionalities, could you bring me some support or ideas of how I can complete that task, please.  

I will appreciate your help so much. 

bye

**Comment by ilg-ul** [comment]
I did not check the OpenOCD sources, but I also remember some problems with the newlib implementation of the `system()` call.

I suggest you check both the OpenOCD and newlib sources.

**Comment by Daparrag** [comment]
could you please specified which are exactly the files in  OpenOCD where is included the implementation for the system calls.

thanks you

**Comment by ilg-ul** [comment]
> which are exactly the files...

sure. aaaa... nope. top secret! ;-)

**Comment by Daparrag** [comment]
thanks for your answers. I will start to work on that.

**Comment by ilg-ul** [comment]
good luck. be sure you fix newlib first.
