### ISSUE TITLE
Flash without debugging?

### ISSUE THREAD

**Issue by dave93cab** [gnuarmeclipse/openocd#6]
Hi,

Not sure if this is the right place, but how do I flash without debugging (using the "Run" option?)

using st-link and stm32f4

Thanks
Dave

**Comment by ilg-ul** [comment]
> Not sure if this is the right place

the right place to ask questions is the project forum.

> how do I flash without debugging (using the "Run" option?)

you provided the answer yourself, using the Run option. 

however please note that this is actually a debug session with all breakpoints disabled.
