### ISSUE TITLE
STM32F4 Discovery init mode failed

### ISSUE THREAD

**Issue by tlamb96** [gnuarmeclipse/openocd#9]
When I try to connect via the command:
sudo ./openocd -f board/stm32f4discovery.cfg
I get the following output:
http://pastebin.com/dcPBQ52Q
I have googled and cannot find an answer. I have the 49-stlinkv2.rules, 99-openocd.rules, and stlink.conf in my /etc/udev/rules.d folder. I have the most recent firmware on my board from here:
http://www.st.com/content/st_com/en/products/embedded-software/development-tool-software/stsw-link004.html
Do you know what's going wrong?

**Comment by ilg-ul** [comment]
for general support please use the project forum.

**Comment by tlamb96** [comment]
My STM32F4 board was shipped with Read Out Protection to level 1 which disables any writing to the memory. As an STM32 novice, this took quite a lot of time to figure out but is now fixed.

**Comment by ilg-ul** [comment]
ok, thank you for the info.
